#!/usr/bin/python2
from sneakers import Exfil
from sneakers import util

mod = "file"

enc = ["b64"]

dataz = "very secret and private message"

encoders = util.list_encoders(verbose=True)
for encoder in encoders:
    print "Encoder name: {0}".format(encoder['encoder'])
    print "Info: {0}".format(encoder['info'])
    print "="*20

t = Exfil(mod, enc)
t.set_channel_params({'sending': {'filename': 'test.txt'}})
t.set_channel_params({'receiving': {'filename': 'test.txt'}})
t.set_encoder_params(enc[0], {})

print t.channel_config()
print t.encoder_config(enc[0])

t.send(dataz)

print t.receive()
