#!/usr/bin/python2
from sneakers import Exfil

mod = "file"

enc = ["b64"]

dataz = "very secret and private message"

print "Possible encoders:"
print Exfil.list_encoders()
print ""

t = Exfil(mod, enc)
t.set_channel_params({'sending': {'filename': 'test.txt'},
                      'receiving': {'filename': 'test.txt'}})
t.set_encoder_params(enc[0], {})

print "Channel configuration:"
print t.channel_config()
print ""

print "Encoder 0 configuration:"
print t.encoder_config(enc[0])
print ""

t.send(dataz)

print "Recieved data:"
print t.receive()
